# Generated by Django 4.2 on 2023-11-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='banner',
        ),
        migrations.AddField(
            model_name='product',
            name='banner',
            field=models.ManyToManyField(related_name='products_banners', to='store.banner', verbose_name='Баннер'),
        ),
    ]
