# Generated by Django 4.2 on 2023-10-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('images', models.ImageField(upload_to='img_banner/%Y/%m/%d', verbose_name='Изображение')),
                ('link', models.URLField(max_length=255, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Отредактирована')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'db_table': 'banners',
                'ordering': ['name', 'slug'],
            },
        ),
    ]
