# Generated by Django 4.2 on 2023-11-09 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='banner',
        ),
        migrations.AddField(
            model_name='banner',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Баннер'),
            preserve_default=False,
        ),
    ]
