# Generated by Django 4.2 on 2023-11-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_banner_product_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='banner',
        ),
        migrations.AddField(
            model_name='banner',
            name='product',
            field=models.ManyToManyField(related_name='products_banners', to='store.product', verbose_name='Баннер'),
        ),
    ]
