# Generated by Django 4.2 on 2023-11-05 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='images',
        ),
        migrations.AddField(
            model_name='banner',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, max_length=255, verbose_name='Ссылка'),
        ),
    ]
