# Generated by Django 4.2 on 2023-11-05 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_banner_images_banner_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='banner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.banner', verbose_name='Баннер'),
            preserve_default=False,
        ),
    ]
